apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30030
      targetPort: 3000
  selector:
    app: grafana
