apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
spec:
  type: NodePort
  ports:
    - port: 4317
      targetPort: 4317
      nodePort: 30417
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      nodePort: 30418
      name: otlp-http
  selector:
    app: otel-collector
