apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30090
      targetPort: 9090
  selector:
    app: prometheus
